### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ghost** [CsokiHUN/fl_dashboard#3]
Nem működik az esx 1.9.1 en a támogatás részlegben a jármű illetve a pénz részleg. Nem adja le a kocsit illetve s pénzt de adja ide. Az item részleg működik

**Comment by CsokiHUN** [comment]
Javítva lett (https://github.com/CsokiHUN/fl_dashboard/commit/ed147353a927d33c7115fd4c6596187c0545ffd6)
